## Parsing of data

The first step to analysis is to parse raw data, which involves the following steps

1) Extracting data from the source
   - Which can come from many sources (excel, csv, json, databases)

2) Cleaning the data
   - Once a sanity check has been done, we need to clean the data 
     appropriately so that it can be utilised for analysis
   - e.g. missing data/ values

## The world of arrays with Numpy

### What is Numpy?
- a python package that was created for scientific computing
- it helps handle large multidimensional arrays and matrices
- a numpy array requires much less memory to store the
    same aount of data compared to a python list
    - this is good because it helps reading/writing from the array in a faster manner

### Creating an array

In [3]:
import numpy as np
n_array = np.array([[0,1,2,3], [4,5,6,7],[8,9,10,11]])

In [4]:
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##### Let's investigate the attributes of this numpy array object

ndim:
    This gives the number of dimensions of the array

In [5]:
n_array.ndim

2

shape: this gives the size of each dimension of the array

In [6]:
n_array.shape   #(row,column)

(3, 4)

size: returns the number of elements

In [8]:
n_array.size

12

dtype: gives the datatype of the elements in the array

In [9]:
n_array.dtype.name

'int64'

## Mathematical operations

   ### Array subtraction

this substracts the a array from the b array to get the resultant c array. The subtraction is elementwise.

In [11]:
a = np.array([11,12,13,14])
b = np.array([1,2,3,4])
c = a-b

In [12]:
c

array([10, 10, 10, 10])

### Squaring an array

In [14]:
# squares it elemenwise
b**2

array([ 1,  4,  9, 16])

In [15]:
### trigonometric function performed on the array

np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Conditional operations

conditional operation is applied to each of the elements of the array to generate respective bool vals

In [16]:
b<2

array([ True, False, False, False])

In [17]:
b

array([1, 2, 3, 4])

### Matrix multiplication 

Element by element multiplication

In [18]:
A1 = np.array([[1,1],[0,1]])
A2 = np.array([[2,0],[3,4]])
A1*A2

array([[2, 0],
       [0, 4]])

The dot product can be performed below

In [19]:
np.dot(A1,A2)

array([[5, 4],
       [3, 4]])

### Indexing and slicing

If you want to select a particular element of an array, it can be achieved using indexes:

In [21]:
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
n_array[0,1]  #0: selects first array, 1: selects the 2nd val in that array (coz 1st val is index 0)

1

In [22]:
n_array[0,0]

0

In [23]:
n_array[1,0]

4

If a range of values has to be selected on a row, then we can use the following
command:

In [24]:
n_array[0,0:3]   #The 0:3 value selects the first three values of the first row.

array([0, 1, 2])

The whole row of values can be selected with the following command:

In [25]:
n_array[0,:]

array([0, 1, 2, 3])

Using the following command, an entire column of values need to be selected:

In [26]:
n_array[:,1]

array([1, 5, 9])

In [27]:
n_array[:,0]

array([0, 4, 8])

### Shape manipulation

The following command flattens the array:

In [28]:
n_array.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

The following command reshapes the array in to a six rows and two columns format.
Also, note that when reshaping, the new shape should have the same number of
elements as the previous one

In [29]:
n_array.shape = (6,2)

In [30]:
n_array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

to transpose

In [31]:
n_array.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## Empowering data analysis with pandas

Pandas?
it's a library that is specially designed for data analysis
it has efficient data structures to process data, perform fast joins, and read data from various sources, etc

### The data structure of pandas

The pandas library essentially has 3 data structures
    1. Series
    2. DataFrame
    3. Panel

### Series

?: a 1-dimensional array, can hold any kinda data and python objects too

In [33]:
import pandas as pd
pd.Series(np.random.randn(5))

0   -0.074332
1   -0.176873
2    1.375655
3   -0.136901
4    0.274922
dtype: float64

random.randn:
    - part of NumPy package and generates random numbers

Series:
    - creates a pandas series that consists of an index (1st col) and 2nd col consists of random val

In [35]:
pd.Series(np.random.randn(5), index=['a','b','c','d','e'])

a   -0.237296
b   -1.547197
c   -0.441773
d    1.463760
e   -1.123030
dtype: float64

A series can be derived from a python dict too:

In [36]:
d = {'A': 10, 'B': 20, 'C': 30}
pd.Series(d)

A    10
B    20
C    30
dtype: int64


### DataFrame

/What is a dataframe?/

DataFrame is a 2D data structure with columns that can be of different datatypes. 
Itcan be seen as a table. 

A DataFrame can be formed from the following data structures
- A NumPy array
- Lists
- Dicts
- Series
- A 2D NumPy array

A dataframe can be created from a dict of series by calling the following commands:

In [37]:
d = {'c1': pd.Series(['A','B','C']), 'c2': pd.Series([1,2.,3.,4.])}
df = pd.DataFrame(d)
df

c1   c2
0    A  1.0
1    B  2.0
2    C  3.0
3  NaN  4.0

The DataFrame can be created using a dict of lists too:

In [40]:
d = {'c1': ['A', 'B', 'C', 'D'], 'c2': [1, 2.0, 3.0, 4.0]}
df = pd.DataFrame(d)
print(df)

  c1   c2
0  A  1.0
1  B  2.0
2  C  3.0
3  D  4.0


### Panel

What is a panel?
A Panel is a data structure that handles 3D data.

The following command is an example of panel data:

In [41]:
d = {'Item1': pd.DataFrame(np.random.randn(4,3)), 'Item2': pd.DataFrame(np.random.rand(4,2))}

In [42]:
pd.Panel(d)

/Users/piramol/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3296: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2

## Inserting and exporting data

In [49]:
d = pd.read_csv('Student_Weight_Status_Category_ Reporting_Results__Beginning_2010.csv')

In [52]:
d[0:5]

Column                              Description
0  LOCATION CODE                    Unique location code
1        COUNTY         The county the school belongs to
2      AREA NAME      The district the school belongs to
3        REGION         The region the school belongs to
4  SCHOOL YEARS   The school year the data is addressing

In [56]:
import json

In [58]:
json_data = open('Student_Weight_Status_Category_ Reporting_Results__Beginning_2010.json')



## Data Cleansing

### Checking the missing data 

In [65]:
d = pd.read_csv('Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv')

In [67]:
d[0:5]['AREA NAME']

0    STATEWIDE (EXCLUDING NYC)
1    STATEWIDE (EXCLUDING NYC)
2    STATEWIDE (EXCLUDING NYC)
3    STATEWIDE (EXCLUDING NYC)
4    STATEWIDE (EXCLUDING NYC)
Name: AREA NAME, dtype: object

In [70]:
d['Location 1'].isnull()

0        True
1        True
2        True
3        True
4        True
5        True
6        True
7        True
8        True
9        True
10       True
11       True
12       True
13       True
14       True
15       True
16       True
17       True
18       True
19       True
20       True
21       True
22       True
23       True
24       True
25       True
26       True
27       True
28       True
29       True
        ...  
8892    False
8893    False
8894    False
8895    False
8896    False
8897    False
8898    False
8899    False
8900    False
8901    False
8902    False
8903    False
8904    False
8905    False
8906    False
8907    False
8908    False
8909    False
8910     True
8911     True
8912     True
8913     True
8914     True
8915     True
8916     True
8917     True
8918     True
8919     True
8920     True
8921     True
Name: Location 1, Length: 8922, dtype: bool

In [71]:
d['Location 1'].isnull().value_counts()    #if its null, i.e. returns true, its a missing val

False    8141
True      781
Name: Location 1, dtype: int64

The preceding command shows that the Location 1 column has 24 instances of
missing values. These missing values can be handled by either removing the rows
with the missing values or replacing it with some values. To remove the rows,
execute the following command:

In [72]:
d = d['Location 1'].dropna()

To remove all the rows with an instance of missing values, use the following command:

In [73]:
d = d.dropna(how='any')

## Filling the missing data

Let's define some DataFrames to work with:

In [76]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a0', 'a10',
                    'a20', 'a30', 'a40'],
                    columns=['X', 'Y', 'Z'])

In [77]:
df

X         Y         Z
a0   0.231152  1.193836 -0.397602
a10  0.500342 -0.407579  1.158172
a20 -0.128943 -0.077166  0.929488
a30  0.719838 -0.306443  0.464645
a40  0.049931 -0.299181  0.265057

Now let's add some extra row indexes, which will create null values in our DF

In [79]:
df2 = df.reindex(['a0', 'a1', 'a10', 'a11', 'a20', 'a21',
                'a30', 'a31', 'a40', 'a41'])

In [80]:
df2

X         Y         Z
a0   0.231152  1.193836 -0.397602
a1        NaN       NaN       NaN
a10  0.500342 -0.407579  1.158172
a11       NaN       NaN       NaN
a20 -0.128943 -0.077166  0.929488
a21       NaN       NaN       NaN
a30  0.719838 -0.306443  0.464645
a31       NaN       NaN       NaN
a40  0.049931 -0.299181  0.265057
a41       NaN       NaN       NaN

Let's replace the null values with a zero:

In [81]:
df2.fillna(0)

X         Y         Z
a0   0.231152  1.193836 -0.397602
a1   0.000000  0.000000  0.000000
a10  0.500342 -0.407579  1.158172
a11  0.000000  0.000000  0.000000
a20 -0.128943 -0.077166  0.929488
a21  0.000000  0.000000  0.000000
a30  0.719838 -0.306443  0.464645
a31  0.000000  0.000000  0.000000
a40  0.049931 -0.299181  0.265057
a41  0.000000  0.000000  0.000000

If you want to fill the value with forward propagation, which means that the
value previous to the null value in the column will be used to fill the null value,
the following command can be used:

In [82]:
df2.fillna(method='pad')  #filling with forward propagation

X         Y         Z
a0   0.231152  1.193836 -0.397602
a1   0.231152  1.193836 -0.397602
a10  0.500342 -0.407579  1.158172
a11  0.500342 -0.407579  1.158172
a20 -0.128943 -0.077166  0.929488
a21 -0.128943 -0.077166  0.929488
a30  0.719838 -0.306443  0.464645
a31  0.719838 -0.306443  0.464645
a40  0.049931 -0.299181  0.265057
a41  0.049931 -0.299181  0.265057

If you want to fill the null values of the column with the column mean, then the
following command can be utilized:

In [83]:
df2.fillna(df2.mean())

X         Y         Z
a0   0.231152  1.193836 -0.397602
a1   0.274464  0.020693  0.483952
a10  0.500342 -0.407579  1.158172
a11  0.274464  0.020693  0.483952
a20 -0.128943 -0.077166  0.929488
a21  0.274464  0.020693  0.483952
a30  0.719838 -0.306443  0.464645
a31  0.274464  0.020693  0.483952
a40  0.049931 -0.299181  0.265057
a41  0.274464  0.020693  0.483952

### String operations

Sometimes, you would want to modify the string field column in your data.
The following technique explains some of the string operations:

#### Substring: 

Let's start by choosing the first five rows of the AREA NAME
column in the data as our sample data to modify:

In [84]:
df = pd.read_csv('Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv')

In [86]:
df['AREA NAME'][0:5]

0    STATEWIDE (EXCLUDING NYC)
1    STATEWIDE (EXCLUDING NYC)
2    STATEWIDE (EXCLUDING NYC)
3    STATEWIDE (EXCLUDING NYC)
4    STATEWIDE (EXCLUDING NYC)
Name: AREA NAME, dtype: object

In order to extract the first word from the Area Name column, we'll use the
extract function as shown in the following command:

In [87]:
df['AREA NAME'][0:5].str.extract('(\w+)')

0
0  STATEWIDE
1  STATEWIDE
2  STATEWIDE
3  STATEWIDE
4  STATEWIDE

In the preceding command, the str attribute of the series is utilized. The str
class contains an extract method, where a regular expression could be fed
to extract data, which is very powerful. It is also possible to extract a second
word in AREA NAME as a separate column:

In [88]:
df['AREA NAME'][0:5].str.extract('(\w+)\s(\w+)')

0    1
0  EXCLUDING  NYC
1  EXCLUDING  NYC
2  EXCLUDING  NYC
3  EXCLUDING  NYC
4  EXCLUDING  NYC

To extract data in different columns, the respective regular expression needs
to be enclosed in separate parentheses.

#### Filtering

If we want to filter rows with data on ELEMENTARY school, then the
following command can be used:

In [89]:
df[df['GRADE LEVEL']=='ELEMENTARY']

LOCATION CODE                     COUNTY  \
1                 0  STATEWIDE (EXCLUDING NYC)   
4                 0  STATEWIDE (EXCLUDING NYC)   
7                 0  STATEWIDE (EXCLUDING NYC)   
10                0  STATEWIDE (EXCLUDING NYC)   
13                1                     ALBANY   
16                1                     ALBANY   
19                1                     ALBANY   
22                1                     ALBANY   
25                2                   ALLEGANY   
28                2                   ALLEGANY   
31                2                   ALLEGANY   
34                2                   ALLEGANY   
37                3                     BROOME   
40                3                     BROOME   
43                3                     BROOME   
46                3                     BROOME   
49                4                CATTARAUGUS   
52                4                CATTARAUGUS   
55                4                CATTARAUGUS   
58                4                CATTARAUGUS   
61                5                     CAYUGA   
64                5                     CAYUGA   
67                5                     CAYUGA   
70                5                     CAYUGA   
73                6                 CHAUTAUQUA   
76                6                 CHAUTAUQUA   
79                6                 CHAUTAUQUA   
82                6                 CHAUTAUQUA   
85                7                    CHEMUNG   
88                7                    CHEMUNG   
...             ...                        ...   
8833         670201                    WYOMING   
8836         670201                    WYOMING   
8839         670401                    WYOMING   
8842         670401                    WYOMING   
8845         670401                    WYOMING   
8848         670401                    WYOMING   
8851         671002                    WYOMING   
8854         671002                    WYOMING   
8857         671002                    WYOMING   
8860         671002                    WYOMING   
8863         671201                    WYOMING   
8866         671201                    WYOMING   
8869         671201                    WYOMING   
8872         671201                    WYOMING   
8875         671501                    WYOMING   
8878         671501                    WYOMING   
8881         671501                    WYOMING   
8884         671501                    WYOMING   
8887         680601                      YATES   
8890         680601                      YATES   
8893         680601                      YATES   
8896         680601                      YATES   
8899         680801                      YATES   
8902         680801                      YATES   
8905         680801                      YATES   
8908         680801                      YATES   
8911         700000                        NaN   
8914         700000                        NaN   
8917         700000                        NaN   
8920         700000                        NaN   

                               AREA NAME                     REGION  \
1              STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
4              STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
7              STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
10             STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
13                                ALBANY      NORTHEASTERN NEW YORK   
16                                ALBANY      NORTHEASTERN NEW YORK   
19                                ALBANY      NORTHEASTERN NEW YORK   
22                                ALBANY      NORTHEASTERN NEW YORK   
25                              ALLEGANY           WESTERN NEW YORK   
28                              ALLEGANY           WESTERN NEW YORK   
31                              ALLEGANY           WESTERN NEW YORK   
34                              ALLEGANY           WE

#### Uppercase

To convert the area name to uppercase, we'll use the
following command:

In [90]:
df['AREA NAME'][0:5].str.upper()

0    STATEWIDE (EXCLUDING NYC)
1    STATEWIDE (EXCLUDING NYC)
2    STATEWIDE (EXCLUDING NYC)
3    STATEWIDE (EXCLUDING NYC)
4    STATEWIDE (EXCLUDING NYC)
Name: AREA NAME, dtype: object

Since the data strings are in uppercase already, there won't be any
difference seen.

#### Lowercase

To convert Area Name to lowercase, we'll use the
following command:

In [91]:
df['AREA NAME'][0:5].str.lower()

0    statewide (excluding nyc)
1    statewide (excluding nyc)
2    statewide (excluding nyc)
3    statewide (excluding nyc)
4    statewide (excluding nyc)
Name: AREA NAME, dtype: object

#### Length:

To find the length of each element of the Area Name column, we'll
use the following command:

In [92]:
df['AREA NAME'][0:5].str.len()

0    25
1    25
2    25
3    25
4    25
Name: AREA NAME, dtype: int64

#### Split

To split Area Name based on a whitespace, we'll use the following command:

In [93]:
df['AREA NAME'][0:5].str.split(' ')

0    [STATEWIDE, (EXCLUDING, NYC)]
1    [STATEWIDE, (EXCLUDING, NYC)]
2    [STATEWIDE, (EXCLUDING, NYC)]
3    [STATEWIDE, (EXCLUDING, NYC)]
4    [STATEWIDE, (EXCLUDING, NYC)]
Name: AREA NAME, dtype: object

In [94]:
df['AREA NAME'][0:5]

0    STATEWIDE (EXCLUDING NYC)
1    STATEWIDE (EXCLUDING NYC)
2    STATEWIDE (EXCLUDING NYC)
3    STATEWIDE (EXCLUDING NYC)
4    STATEWIDE (EXCLUDING NYC)
Name: AREA NAME, dtype: object

#### Replace

If we want to replace all the area names ending with DISTRICT to
DIST, then the following command can be used:

In [100]:
df['AREA NAME'][0:10].str.replace('NYC$', 'new york baby')

0    STATEWIDE (EXCLUDING NYC)
1    STATEWIDE (EXCLUDING NYC)
2    STATEWIDE (EXCLUDING NYC)
3    STATEWIDE (EXCLUDING NYC)
4    STATEWIDE (EXCLUDING NYC)
5    STATEWIDE (EXCLUDING NYC)
6    STATEWIDE (EXCLUDING NYC)
7    STATEWIDE (EXCLUDING NYC)
8    STATEWIDE (EXCLUDING NYC)
9    STATEWIDE (EXCLUDING NYC)
Name: AREA NAME, dtype: object

Replace method:
    1st argument - regular expression used to identify the portion of the string to replace
    2nd arg: value for it to be replaced with


## Merging data

To combine datasets together, the concat function of pandas can be utilized.
Let's take the Area Name and the County columns with its first five rows:

In [109]:
df.head()

LOCATION CODE                     COUNTY                  AREA NAME  \
0              0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
1              0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
2              0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
3              0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   
4              0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)   

                      REGION SCHOOL YEARS  NO. OVERWEIGHT  PCT OVERWEIGHT  \
0  STATEWIDE (EXCLUDING NYC)    2010-2012         77813.0            16.2   
1  STATEWIDE (EXCLUDING NYC)    2010-2012         44970.0            15.8   
2  STATEWIDE (EXCLUDING NYC)    2010-2012         33004.0            16.8   
3  STATEWIDE (EXCLUDING NYC)    2012-2014         83095.0            16.7   
4  STATEWIDE (EXCLUDING NYC)    2012-2014         47868.0            16.4   

   NO. OBESE  PCT OBESE  NO. OVERWEIGHT OR OBESE  PCT OVERWEIGHT OR OBESE  \
0    84578.0       17.6                 162391.0                     33.7   
1    48843.0       17.2                  93813.0                     33.0   
2    35719.0       18.2                  68723.0                     35.0   
3    86016.0       17.3                 169111.0                     33.9   
4    49140.0       16.8                  97008.0                     33.1   

      GRADE LEVEL                  AREA TYPE STREET ADDRESS CITY STATE  \
0  DISTRICT TOTAL  STATEWIDE (EXCLUDING NYC)            NaN  NaN   NaN   
1      ELEMENTARY  STATEWIDE (EXCLUDING NYC)            NaN  NaN   NaN   
2     MIDDLE/HIGH  STATEWIDE (EXCLUDING NYC)            NaN  NaN   NaN   
3  DISTRICT TOTAL  STATEWIDE (EXCLUDING NYC)            NaN  NaN   NaN   
4      ELEMENTARY  STATEWIDE (EXCLUDING NYC)            NaN  NaN   NaN   

   ZIP CODE Location 1  
0       NaN        NaN  
1       NaN        NaN  
2       NaN        NaN  
3       NaN        NaN  
4       NaN        NaN

In [110]:
df[['AREA NAME', 'COUNTY']][0:5]

AREA NAME                     COUNTY
0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
1  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
2  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
3  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
4  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)

In [112]:
p1 = df[['AREA NAME', 'COUNTY']][0:2]
p2 = df[['AREA NAME', 'COUNTY']][2:5]

The first two rows of the data are in p1 and the last three rows are in p2. These pieces
can be combined using the concat() function:

In [113]:
pd.concat([p1,p2])

AREA NAME                     COUNTY
0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
1  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
2  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
3  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
4  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)

The combined pieces can be identified by assigning a key:

In [114]:
concatenated = pd.concat([p1,p2], keys = ['p1','p2'])

In [115]:
concatenated

AREA NAME                     COUNTY
p1 0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
   1  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
p2 2  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
   3  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
   4  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)

Using the keys, the pieces can be extracted back from the concatenated data:

In [116]:
concatenated.ix['p1']

/Users/piramol/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


AREA NAME                     COUNTY
0  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)
1  STATEWIDE (EXCLUDING NYC)  STATEWIDE (EXCLUDING NYC)


## Data operations
Once the missing data is handled, various operations can be performed on the data.

## Aggregation operations

There are a number of aggregation operations, such as average, sum, and so on,
which you would like to perform on a numerical field. These are the methods
used to perform it:

### Average:

To find out the average number of students in the ELEMENTARY
school who are obese, we'll first filter the ELEMENTARY data with the
following command:

In [118]:
data = df[df['GRADE LEVEL'] == 'ELEMENTARY']

In [119]:
data['NO. OBESE'].mean()

275.78676207513416

The elementary grade level data is filtered and stored in the data object. The
NO. OBESE column is selected, which contains the number of obese students
and using the mean() method, the average is taken out.

### Sum:

To find out the total number of elementary students who are obese
across all the school, use the following command:

In [120]:
data['NO. OBESE'].sum()

770824.0

### Max:

To get the maximum number of students that are obese in an
elementary school, use the following command:

In [121]:
data['NO. OBESE'].max()

49140.0

### Min:

To get the minimum number of students that are obese in an
elementary school, use the following command:

In [122]:
data['NO. OBESE'].min()

5.0

### STD:

To get the standard deviation of the number of obese students, use the
following command:

In [124]:
data['NO. OBESE'].std()

2021.1248151905831

### Count:

To count the total number of schools with the ELEMENTARY grade in
the DELAWARE county, use the following command:

## Joins

SQL-like joins can be performed on the DataFrame using pandas. Let's define
a lookup DataFrame, which assigns levels to each of the grades using the
following command:

In [126]:
grade_lookup = {'GRADE LEVEL': pd.Series(['ELEMENTARY',
                'MIDDLE/HIGH', 'MISC']),
                'LEVEL': pd.Series([1, 2, 3])}

In [129]:
import pandas as pd
grade_lookup = pd.DataFrame(grade_lookup)

Let's take the first five rows of the GRADE data column as an example for performing
the joins:

In [130]:
df[['GRADE LEVEL']][0:5]

GRADE LEVEL
0  DISTRICT TOTAL
1      ELEMENTARY
2     MIDDLE/HIGH
3  DISTRICT TOTAL
4      ELEMENTARY